server:
  port: 8081

spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:postgresql://postgres:5432/swiftpay
    username: swiftpay
    password: swiftpay
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ledger-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      # Change these to standard deserializers to unblock programmatic overrides
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

logging:
  level:
    root: INFO